version: '3.7'

services:

  php:
    image: php:8.2-cli
    build: .
    tty: true
    working_dir: /php
    # command:
    #   # - php -S 0.0.0.0:9000 /php/covid_api.php
    ports:
      - 9000:9000
    volumes:
      - .:/php